/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.28
 * Generated at: 2024-09-01 07:38:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import com.revature.ecom.Models.messageModel;
import com.revature.ecom.Models.userModel;
import com.revature.ecom.DAO.categoryDAO;
import com.revature.ecom.Models.adminModel;
import com.revature.ecom.Models.cartModel;
import com.revature.ecom.DAO.cartDAO;
import com.revature.ecom.Models.userModel;
import java.util.List;
import com.revature.ecom.Models.categoryModel;
import com.revature.ecom.Utils.DatabaseUtil;
import com.revature.ecom.DAO.categoryDAO;
import com.revature.ecom.Models.messageModel;
import com.revature.ecom.Models.messageModel;
import com.revature.ecom.Models.userModel;
import com.revature.ecom.Models.messageModel;
import com.revature.ecom.Models.productModel;
import com.revature.ecom.DAO.productDAO;
import com.revature.ecom.Models.wishlistModel;
import java.util.List;
import com.revature.ecom.Models.userModel;
import com.revature.ecom.Utils.DatabaseUtil;
import com.revature.ecom.DAO.wishlistDAO;
import com.revature.ecom.Models.messageModel;
import com.revature.ecom.Models.orderedProductModel;
import com.revature.ecom.Models.orderModel;
import java.util.List;
import com.revature.ecom.DAO.orderedProductDAO;
import com.revature.ecom.DAO.orderDAO;
import com.revature.ecom.Utils.DatabaseUtil;
import com.revature.ecom.Models.userModel;

public final class profile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/wishlist.jsp", Long.valueOf(1725175782764L));
    _jspx_dependants.put("/personalInfo.jsp", Long.valueOf(1725029945310L));
    _jspx_dependants.put("/Components/alert_message.jsp", Long.valueOf(1724990341171L));
    _jspx_dependants.put("/Components/navbar.jsp", Long.valueOf(1725132993796L));
    _jspx_dependants.put("/order.jsp", Long.valueOf(1725175684713L));
    _jspx_dependants.put("/Components/common_css_js.jsp", Long.valueOf(1725114981486L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(23);
    _jspx_imports_classes.add("com.revature.ecom.Models.adminModel");
    _jspx_imports_classes.add("com.revature.ecom.DAO.productDAO");
    _jspx_imports_classes.add("com.revature.ecom.Models.wishlistModel");
    _jspx_imports_classes.add("com.revature.ecom.DAO.orderedProductDAO");
    _jspx_imports_classes.add("com.revature.ecom.Models.productModel");
    _jspx_imports_classes.add("com.revature.ecom.DAO.categoryDAO");
    _jspx_imports_classes.add("com.revature.ecom.Models.cartModel");
    _jspx_imports_classes.add("com.revature.ecom.DAO.wishlistDAO");
    _jspx_imports_classes.add("com.revature.ecom.Utils.DatabaseUtil");
    _jspx_imports_classes.add("com.revature.ecom.DAO.orderDAO");
    _jspx_imports_classes.add("com.revature.ecom.Models.orderModel");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.revature.ecom.DAO.cartDAO");
    _jspx_imports_classes.add("com.revature.ecom.Models.userModel");
    _jspx_imports_classes.add("com.revature.ecom.Models.orderedProductModel");
    _jspx_imports_classes.add("com.revature.ecom.Models.messageModel");
    _jspx_imports_classes.add("com.revature.ecom.Models.categoryModel");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"error_exception.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');

userModel activeUser = (userModel) session.getAttribute("activeUser");
if (activeUser == null) {
    messageModel message = new messageModel("You are not logged in! Login first!!", "error", "alert-danger");
    session.setAttribute("message", message);
    response.sendRedirect("login.jsp");
    return;  
}

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"ISO-8859-1\">\n");
      out.write("<title>My Profile</title>\n");
      out.write("<!--CSS-->\n");
      out.write("<link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM\" crossorigin=\"anonymous\">\n");
      out.write("<!--font awesome-->\n");
      out.write("<!--<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\n");
      out.write("-->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"CSS/style.css\"/>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!--JavaScript-->\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"JS/script.js\"></script>\n");
      out.write("\n");
      out.write("<!--jQuery-->\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.7.0.min.js\" integrity=\"sha256-2Pmvv0kuTBOenSvLm6bvfBSSHrUJ+3A7x6P5Ebd07/g=\" crossorigin=\"anonymous\"></script>\n");
      out.write("<!--sweet alert-->\n");
      out.write("<script src=\"https://unpkg.com/sweetalert/dist/sweetalert.min.js\"></script>\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("    body {\n");
      out.write("        font-family: Arial, sans-serif;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .cus-active {\n");
      out.write("        background-color: #007bff !important;\n");
      out.write("        color: white !important;\n");
      out.write("        font-weight: bold;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list-btn {\n");
      out.write("        font-size: 18px;\n");
      out.write("        padding: 12px;\n");
      out.write("        border: 1px solid #ddd;\n");
      out.write("        border-radius: 8px;\n");
      out.write("        background-color: #f1f1f1;\n");
      out.write("        cursor: pointer;\n");
      out.write("        text-align: left;\n");
      out.write("        margin-bottom: 5px;\n");
      out.write("        transition: background-color 0.3s, color 0.3s;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list-btn:hover {\n");
      out.write("        background-color: #e2e6ea;\n");
      out.write("        color: #0056b3;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .list-btn:active {\n");
      out.write("        background-color: #d1d1d1;\n");
      out.write("        color: #003d7a;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .profile-header {\n");
      out.write("        display: flex;\n");
      out.write("        align-items: center;\n");
      out.write("        border-bottom: 2px solid #ddd;\n");
      out.write("        padding: 20px;\n");
      out.write("        background-color: #f8f9fa;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .profile-header img {\n");
      out.write("        border-radius: 50%;\n");
      out.write("        max-width: 80px;\n");
      out.write("        margin-right: 15px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .profile-header h5 {\n");
      out.write("        margin: 0;\n");
      out.write("        font-size: 24px;\n");
      out.write("        color: #333;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card-header {\n");
      out.write("        background-color: #007bff;\n");
      out.write("        color: white;\n");
      out.write("        padding: 15px;\n");
      out.write("        border-radius: 0.25rem 0.25rem 0 0;\n");
      out.write("        font-size: 18px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .card-body {\n");
      out.write("        padding: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal-header {\n");
      out.write("        background-color: #007bff;\n");
      out.write("        color: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal-body {\n");
      out.write("        padding: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal-header .btn-close {\n");
      out.write("        background-color: #007bff;\n");
      out.write("        color: white;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal-footer .btn-primary {\n");
      out.write("        background-color: #007bff;\n");
      out.write("        border: none;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-card {\n");
      out.write("        border: 1px solid #ddd;\n");
      out.write("        border-radius: 0.5rem;\n");
      out.write("        margin-bottom: 15px;\n");
      out.write("        background-color: #ffffff;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .sidebar-card .card-body {\n");
      out.write("        padding: 20px;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .modal-content {\n");
      out.write("        border-radius: 0.5rem;\n");
      out.write("    }\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <!-- Navbar -->\n");
      out.write("    ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

userModel user = (userModel) session.getAttribute("activeUser");
adminModel admin = (adminModel) session.getAttribute("activeAdmin");

categoryDAO catDao = new categoryDAO(DatabaseUtil.getConnection());
List<categoryModel> categoryList = catDao.getAllCategories();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("/* General navbar styling */\r\n");
      out.write(".navbar {\r\n");
      out.write("    background-color: #34495e;\r\n");
      out.write("    padding: 1rem;\r\n");
      out.write("    box-shadow: 0px 4px 10px rgba(0, 0, 0, 0.3);\r\n");
      out.write("    max-height:15vh;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-brand {\r\n");
      out.write("    font-size: 1.6rem;\r\n");
      out.write("    font-weight: bold;\r\n");
      out.write("    color: #ecf0f1 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link {\r\n");
      out.write("    color: #bdc3c7 !important;\r\n");
      out.write("    margin-right: 1rem;\r\n");
      out.write("    transition: color 0.3s, background-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".nav-link:hover {\r\n");
      out.write("    color: #ecf0f1 !important;\r\n");
      out.write("    background-color: rgba(255, 255, 255, 0.1);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler {\r\n");
      out.write("    border-color: #ecf0f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-toggler-icon {\r\n");
      out.write("    background-image: url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 30 30'%3E%3Cpath stroke='rgba%2899, 110, 114, 1%29' stroke-width='2' linecap='round' linejoin='round' d='M4 7h22M4 15h22M4 23h22'/%3E%3C/svg%3E\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-menu {\r\n");
      out.write("    background-color: #2c3e50 !important;\r\n");
      out.write("    border: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item {\r\n");
      out.write("    color: #bdc3c7 !important;\r\n");
      out.write("    transition: background-color 0.3s, color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".dropdown-item:hover {\r\n");
      out.write("    background-color: #34495e !important;\r\n");
      out.write("    color: #ecf0f1 !important;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".badge {\r\n");
      out.write("    font-size: 0.75rem;\r\n");
      out.write("    background-color: #e74c3c;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Button styling */\r\n");
      out.write(".btn-outline-light {\r\n");
      out.write("    color: #bdc3c7;\r\n");
      out.write("    border-color: #bdc3c7;\r\n");
      out.write("    transition: color 0.3s, border-color 0.3s;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".btn-outline-light:hover {\r\n");
      out.write("    color: #ecf0f1;\r\n");
      out.write("    border-color: #ecf0f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Flexbox alignment */\r\n");
      out.write(".navbar-nav {\r\n");
      out.write("    display: flex;\r\n");
      out.write("    align-items: center;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .nav-item {\r\n");
      out.write("    margin-right: 0rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control {\r\n");
      out.write("    background-color: #2c3e50 !important;\r\n");
      out.write("    border: none;\r\n");
      out.write("    color: #ecf0f1;\r\n");
      out.write("    margin-right: 0.5rem;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control::placeholder {\r\n");
      out.write("    color: #bdc3c7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".form-control:focus {\r\n");
      out.write("    box-shadow: none;\r\n");
      out.write("    border-color: #ecf0f1;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("@media (max-width: 992px) {\r\n");
      out.write("    .navbar-collapse {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .navbar-nav {\r\n");
      out.write("        flex-direction: column;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .navbar-nav .nav-item {\r\n");
      out.write("        margin-right: 0;\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .form-control {\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("/* Specific logo styles */\r\n");
      out.write(".navbar-nav .register-link {\r\n");
      out.write("    background-image: url('path/to/register-icon.png');\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position: left center;\r\n");
      out.write("    padding-left: 30px; /* Adjust based on the size of the icon */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .buyer-link {\r\n");
      out.write("    background-image: url('path/to/buyer-icon.png');\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position: left center;\r\n");
      out.write("    padding-left: 30px; /* Adjust based on the size of the icon */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".navbar-nav .seller-link {\r\n");
      out.write("    background-image: url('path/to/seller-icon.png');\r\n");
      out.write("    background-repeat: no-repeat;\r\n");
      out.write("    background-position: left center;\r\n");
      out.write("    padding-left: 30px; /* Adjust based on the size of the icon */\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"index.jsp\" style=\"font-weight: bold; font-size: 1.5rem; margin-right:7vh; background: linear-gradient(45deg, #000000, #ff4081, #007bff); -webkit-background-clip: text; -webkit-text-fill-color: transparent;\">\r\n");
      out.write("    <i class=\"fa-sharp fa-solid fa-house\"></i>&ensp;RevShop\r\n");
      out.write("</a>\r\n");
      out.write("\r\n");
      out.write("        <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\"\r\n");
      out.write("            aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("            <span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("        </button>\r\n");
      out.write("        <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\r\n");
      out.write("            ");
 if (admin != null) { 
      out.write("\r\n");
      out.write("            <!-- Admin nav bar -->\r\n");
      out.write("            <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-dark nav-link d-flex align-items-center rounded-pill px-3 py-2 shadow-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#add-category\">\r\n");
      out.write("            <i class=\"fa-solid fa-plus fa-xs me-2\"></i>Add Category\r\n");
      out.write("        </button>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <button type=\"button\" class=\"btn btn-secondary nav-link d-flex align-items-center rounded-pill px-3 py-2 shadow-sm\" data-bs-toggle=\"modal\" data-bs-target=\"#add-product\">\r\n");
      out.write("            <i class=\"fa-solid fa-plus fa-xs me-2\"></i>Add Product\r\n");
      out.write("        </button>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link text-info fw-light d-flex align-items-center\" href=\"admin.jsp\">\r\n");
      out.write("            <i class=\"fa-solid fa-user-circle fa-lg me-2\"></i>");
      out.print(admin.getName());
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link text-danger fw-light d-flex align-items-center\" href=\"logout?user=admin\">\r\n");
      out.write("            <i class=\"fa-solid fa-sign-out-alt fa-lg me-2\"></i>Logout\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            ");
 } else { 
      out.write("\r\n");
      out.write("            <!-- General nav bar -->\r\n");
      out.write("            <!-- Navigation items for products and category -->\r\n");
      out.write("<ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">\r\n");
      out.write("    <li class=\"nav-item\">\r\n");
      out.write("        <a class=\"nav-link text-dark rounded-pill px-3 py-2 shadow-sm d-flex align-items-center\" href=\"products.jsp\" role=\"button\" aria-expanded=\"false\">\r\n");
      out.write("            Products\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item dropdown\">\r\n");
      out.write("        <a class=\"nav-link dropdown-toggle text-dark rounded-pill px-3 py-2 shadow-sm d-flex align-items-center\" href=\"#\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\r\n");
      out.write("            Category\r\n");
      out.write("        </a>\r\n");
      out.write("        <ul class=\"dropdown-menu\">\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"products.jsp?category=0\">All Products</a></li>\r\n");
      out.write("            ");
 for (categoryModel c : categoryList) { 
      out.write("\r\n");
      out.write("            <li><a class=\"dropdown-item\" href=\"products.jsp?category=");
      out.print(c.getCategoryId());
      out.write('"');
      out.write('>');
      out.print(c.getCategoryName());
      out.write("</a></li>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
      out.write("\r\n");
      out.write("<!-- Search form -->\r\n");
      out.write("<form class=\"d-flex pe-5\" role=\"search\" action=\"products.jsp\" method=\"get\">\r\n");
      out.write("    <input name=\"search\" class=\"form-control me-2 rounded-pill border-0 shadow-sm\" size=\"50\" type=\"search\" placeholder=\"Search for products\" aria-label=\"Search\">\r\n");
      out.write("    <button class=\"btn btn-outline-dark rounded-pill px-4\" type=\"submit\">Search</button>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<!-- User actions for logged-in users -->\r\n");
 if (user != null) {
    cartDAO cartDao = new cartDAO(DatabaseUtil.getConnection());
    int cartCount = cartDao.getCartCountByUserId(user.getUserId());

      out.write("\r\n");
      out.write("<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("    <li class=\"nav-item pe-3\">\r\n");
      out.write("        <a class=\"nav-link position-relative d-flex align-items-center rounded-pill px-3 py-2 shadow-sm\" href=\"cart.jsp\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping me-2\"></i> Cart\r\n");
      out.write("            <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\">");
      out.print(cartCount);
      out.write("</span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item pe-3\">\r\n");
      out.write("        <a class=\"nav-link text-dark rounded-pill px-3 py-2 shadow-sm d-flex align-items-center\" href=\"profile.jsp\">\r\n");
      out.write("            <i class=\"fa-solid fa-user me-2\"></i>");
      out.print(user.getUserName());
      out.write("\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item pe-3\">\r\n");
      out.write("        <a class=\"nav-link text-danger rounded-pill px-3 py-2 shadow-sm d-flex align-items-center\" href=\"logout?user=user\">\r\n");
      out.write("            <i class=\"fa-solid fa-sign-out-alt me-2\"></i> Logout\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
 } else { 
      out.write("\r\n");
      out.write("<!-- User actions for guests -->\r\n");
      out.write("<ul class=\"navbar-nav ms-auto\">\r\n");
      out.write("    <li class=\"nav-item pe-2\">\r\n");
      out.write("        <a class=\"nav-link btn btn-outline-primary rounded-pill px-3 py-2\" href=\"login.jsp\">Login</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item pe-2\">\r\n");
      out.write("        <a class=\"nav-link btn btn-outline-success rounded-pill px-3 py-2\" href=\"adminlogin.jsp\">Seller</a>\r\n");
      out.write("    </li>\r\n");
      out.write("    <li class=\"nav-item pe-3\">\r\n");
      out.write("        <a class=\"nav-link position-relative d-flex align-items-center rounded-pill px-3 py-2 shadow-sm\" href=\"cart.jsp\">\r\n");
      out.write("            <i class=\"fa-solid fa-cart-shopping me-2\"></i> Cart\r\n");
      out.write("            <span class=\"position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger\"></span>\r\n");
      out.write("        </a>\r\n");
      out.write("    </li>\r\n");
      out.write("</ul>\r\n");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("          \r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"container-fluid px-3 py-5\">\n");
      out.write("        <div class=\"row\">\n");
      out.write("            <!-- Sidebar -->\n");
      out.write("            <div class=\"col-md-3\">\n");
      out.write("                <div class=\"card sidebar-card\">\n");
      out.write("                    <div class=\"card-body profile-header\">\n");
      out.write("                        <div class=\"row mt-2 mb-2\">\n");
      out.write("                            <div class=\"col-md-4 text-center\">\n");
      out.write("                                <img src=\"Images/profile.png\" class=\"img-fluid\">\n");
      out.write("                            </div>\n");
      out.write("                            <div class=\"col-md-8\">\n");
      out.write("                                <p>Hello,</p>\n");
      out.write("                                <h5>");
      out.print(activeUser.getUserName());
      out.write("</h5>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card sidebar-card mt-3\">\n");
      out.write("                    <div class=\"list-group\">\n");
      out.write("                        <button type=\"button\" id=\"profile-btn\" class=\"list-btn cus-active\" aria-current=\"true\">\n");
      out.write("                            Profile Information\n");
      out.write("                        </button>\n");
      out.write("                        <button type=\"button\" id=\"wishlist-btn\" class=\"list-btn\">\n");
      out.write("                            My Wishlist\n");
      out.write("                        </button>\n");
      out.write("                        <button type=\"button\" id=\"order-btn\" class=\"list-btn\">\n");
      out.write("                            My Orders\n");
      out.write("                        </button>\n");
      out.write("                        <button type=\"button\" id=\"logout-btn\" class=\"list-btn\" onclick=\"window.open('logout?user=user', '_self')\">\n");
      out.write("                            Logout\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- End of Sidebar -->\n");
      out.write("\n");
      out.write("            <!-- Main Content -->\n");
      out.write("            <div class=\"col-md-9\">\n");
      out.write("                <div class=\"card\">\n");
      out.write("                    <div id=\"profile\">\n");
      out.write("                        ");
      out.write('\n');

messageModel messg = (messageModel) session.getAttribute("message");
if (messg != null) {

      out.write("\n");
      out.write("<div class=\"alert ");
      out.print(messg.getCssClass());
      out.write("\" role=\"alert\" id=\"alert\">\n");
      out.write("	");
      out.print(messg.getMessage());
      out.write("\n");
      out.write("</div>\n");

session.removeAttribute("message");
}

      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("	setTimeout(function() {\n");
      out.write("		$('#alert').alert('close');\n");
      out.write("	}, 3000);\n");
      out.write("</script>");
      out.write("\n");
      out.write("                        ");
      out.write('\n');
      out.write('\n');

userModel user1 = (userModel) session.getAttribute("activeUser");
if (user1 == null) {
	messageModel message = new messageModel("You are not logged in! Login first!!", "error", "alert-danger");
	session.setAttribute("message", message);
	response.sendRedirect("login.jsp");
	return;
}

      out.write("\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("label {\n");
      out.write("	font-weight: bold;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<div class=\"container px-3 py-3\">\n");
      out.write("	<h3>Personal Information</h3>\n");
      out.write("	<form id=\"update-user\" action=\"updateuser\" method=\"post\">\n");
      out.write("		<input type=\"hidden\" name=\"operation\" value=\"updateUser\">\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-6 mt-2\">\n");
      out.write("				<label class=\"form-label\">Your name</label> <input type=\"text\"\n");
      out.write("					name=\"name\" class=\"form-control\" placeholder=\"First and last name\"\n");
      out.write("					value=\"");
      out.print(user1.getUserName());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-md-6 mt-2\">\n");
      out.write("				<label class=\"form-label\">Email</label> <input type=\"email\"\n");
      out.write("					name=\"email\" placeholder=\"Email address\" class=\"form-control\"\n");
      out.write("					value=\"");
      out.print(user1.getUserEmail());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-6 mt-2\">\n");
      out.write("				<label class=\"form-label\">Mobile number</label> <input type=\"number\"\n");
      out.write("					name=\"mobile_no\" placeholder=\"Mobile number\" class=\"form-control\"\n");
      out.write("					value=\"");
      out.print(user1.getUserPhone());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-md-6 mt-5\">\n");
      out.write("				<label class=\"form-label pe-3\">Gender</label>\n");
      out.write("				");

				String gender = user1.getUserGender();
				if (gender.trim().equals("Male")) {
				
      out.write("\n");
      out.write("				<input class=\"form-check-input\" type=\"radio\" name=\"gender\"\n");
      out.write("					value=\"Male\" checked> <span\n");
      out.write("					class=\"form-check-label pe-3 ps-1\"> Male </span> <input\n");
      out.write("					class=\"form-check-input\" type=\"radio\" name=\"gender\" value=\"Female\">\n");
      out.write("				<span class=\"form-check-label ps-1\"> Female </span>\n");
      out.write("\n");
      out.write("				");

				} else {
				
      out.write("\n");
      out.write("				<input class=\"form-check-input\" type=\"radio\" name=\"gender\"\n");
      out.write("					value=\"Male\"> <span class=\"form-check-label pe-3 ps-1\">\n");
      out.write("					Male </span> <input class=\"form-check-input\" type=\"radio\" name=\"gender\"\n");
      out.write("					value=\"Female\" checked> <span class=\"form-check-label ps-1\">\n");
      out.write("					Female </span>\n");
      out.write("				");

				}
				
      out.write("\n");
      out.write("\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"mt-2\">\n");
      out.write("			<label class=\"form-label\">Address</label> <input type=\"text\"\n");
      out.write("				name=\"address\" placeholder=\"Enter Address(Area and Street))\"\n");
      out.write("				class=\"form-control\" value=\"");
      out.print(user1.getUserAddress());
      out.write("\">\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row\">\n");
      out.write("			<div class=\"col-md-6 mt-2\">\n");
      out.write("				<label class=\"form-label\">City</label> <input class=\"form-control\"\n");
      out.write("					type=\"text\" name=\"city\" placeholder=\"City/District/Town\"\n");
      out.write("					value=\"");
      out.print(user1.getUserCity());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("			<div class=\"col-md-6 mt-2\">\n");
      out.write("				<label class=\"form-label\">Pincode</label> <input\n");
      out.write("					class=\"form-control\" type=\"number\" name=\"pincode\"\n");
      out.write("					placeholder=\"Pincode\" maxlength=\"6\"\n");
      out.write("					value=\"");
      out.print(user1.getUserPincode());
      out.write("\">\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div class=\"row mt-2\">\n");
      out.write("			<label class=\"form-label\">State</label>\n");
      out.write("			<div class=\"input-group mb-3\">\n");
      out.write("				<input class=\"form-control\" type=\"text\"\n");
      out.write("					value=\"");
      out.print(user1.getUserState());
      out.write("\">\n");
      out.write("					 <select name=\"state\"\n");
      out.write("					id=\"state-list\" class=\"form-select\">\n");
      out.write("					<option selected>--Select State--</option>\n");
      out.write("					<option value=\"Andaman &amp; Nicobar Islands\">Andaman\n");
      out.write("						&amp; Nicobar Islands</option>\n");
      out.write("					<option value=\"Andhra Pradesh\">Andhra Pradesh</option>\n");
      out.write("					<option value=\"Arunachal Pradesh\">Arunachal Pradesh</option>\n");
      out.write("					<option value=\"Assam\">Assam</option>\n");
      out.write("					<option value=\"Bihar\">Bihar</option>\n");
      out.write("					<option value=\"Chandigarh\">Chandigarh</option>\n");
      out.write("					<option value=\"Chhattisgarh\">Chhattisgarh</option>\n");
      out.write("					<option value=\"Dadra &amp; Nagar Haveli &amp; Daman &amp; Diu\">Dadra\n");
      out.write("						&amp; Nagar Haveli &amp; Daman &amp; Diu</option>\n");
      out.write("					<option value=\"Delhi\">Delhi</option>\n");
      out.write("					<option value=\"Goa\">Goa</option>\n");
      out.write("					<option value=\"Gujarat\">Gujarat</option>\n");
      out.write("					<option value=\"Haryana\">Haryana</option>\n");
      out.write("					<option value=\"Himachal Pradesh\">Himachal Pradesh</option>\n");
      out.write("					<option value=\"Jammu &amp; Kashmir\">Jammu &amp; Kashmir</option>\n");
      out.write("					<option value=\"Jharkhand\">Jharkhand</option>\n");
      out.write("					<option value=\"Karnataka\">Karnataka</option>\n");
      out.write("					<option value=\"Kerala\">Kerala</option>\n");
      out.write("					<option value=\"Ladakh\">Ladakh</option>\n");
      out.write("					<option value=\"Lakshadweep\">Lakshadweep</option>\n");
      out.write("					<option value=\"Madhya Pradesh\">Madhya Pradesh</option>\n");
      out.write("					<option value=\"Maharashtra\">Maharashtra</option>\n");
      out.write("					<option value=\"Manipur\">Manipur</option>\n");
      out.write("					<option value=\"Meghalaya\">Meghalaya</option>\n");
      out.write("					<option value=\"Mizoram\">Mizoram</option>\n");
      out.write("					<option value=\"Nagaland\">Nagaland</option>\n");
      out.write("					<option value=\"Odisha\">Odisha</option>\n");
      out.write("					<option value=\"Puducherry\">Puducherry</option>\n");
      out.write("					<option value=\"Punjab\">Punjab</option>\n");
      out.write("					<option value=\"Rajasthan\">Rajasthan</option>\n");
      out.write("					<option value=\"Sikkim\">Sikkim</option>\n");
      out.write("					<option value=\"Tamil Nadu\">Tamil Nadu</option>\n");
      out.write("					<option value=\"Telangana\">Telangana</option>\n");
      out.write("					<option value=\"Tripura\">Tripura</option>\n");
      out.write("					<option value=\"Uttarakhand\">Uttarakhand</option>\n");
      out.write("					<option value=\"Uttar Pradesh\">Uttar Pradesh</option>\n");
      out.write("					<option value=\"West Bengal\">West Bengal</option>\n");
      out.write("				</select>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("		<div id=\"submit-btn\" class=\"container text-center mt-3\">\n");
      out.write("			<button type=\"submit\" class=\"btn btn-outline-primary me-3\">Update</button>\n");
      out.write("			<button type=\"reset\" class=\"btn btn-outline-primary\">Reset</button>\n");
      out.write("		</div>\n");
      out.write("	</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"wishlist\" style=\"display: none;\">\n");
      out.write("                        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

userModel u1 = (userModel) session.getAttribute("activeUser");
if (u1 == null) {
    messageModel message = new messageModel("You are not logged in! Login first!!", "error", "alert-danger");
    session.setAttribute("message", message);
    response.sendRedirect("login.jsp");
    return;  
}
wishlistDAO wishListDao = new wishlistDAO(DatabaseUtil.getConnection());
List<wishlistModel> wlist = wishListDao.getListByUserId(u1.getUserId());
productDAO pDao = new productDAO(DatabaseUtil.getConnection());

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>My Wishlist</title>\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"styles/custom.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container mt-5\">\n");
      out.write("        ");

        if (wlist == null || wlist.size() == 0) {
        
      out.write("\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("            <img src=\"Images/wishlist.png\" alt=\"Empty Wishlist\" class=\"img-fluid\" style=\"max-width: 250px;\">\n");
      out.write("            <h4 class=\"mt-3\">Empty Wishlist</h4>\n");
      out.write("            <p class=\"lead\">You have no items in your wishlist. Start adding your favorite products!</p>\n");
      out.write("        </div>\n");
      out.write("        ");

        } else {
        
      out.write("\n");
      out.write("        <div class=\"mb-4\">\n");
      out.write("            <h4 class=\"text-primary border-bottom pb-2\">My Wishlist (");
      out.print(wlist.size());
      out.write(")</h4>\n");
      out.write("            <p class=\"text-muted\">Here are the items you have added to your wishlist. You can manage them from this list.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"table-responsive\">\n");
      out.write("            <table class=\"table table-striped table-hover\">\n");
      out.write("                <thead class=\"table-secondary\">\n");
      out.write("                    <tr class=\"text-center\">\n");
      out.write("                        <th>Product</th>\n");
      out.write("                        <th>Name</th>\n");
      out.write("                        <th>Price</th>\n");
      out.write("                        <th>Action</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                    for (wishlistModel w : wlist) {
                        productModel p = pDao.getProductsByProductId(w.getProductId());
                    
      out.write("\n");
      out.write("                    <tr class=\"text-center\">\n");
      out.write("                        <td><img src=\"Product_imgs/");
      out.print(p.getProductImages());
      out.write("\" alt=\"");
      out.print(p.getProductName());
      out.write("\" class=\"img-thumbnail\" style=\"max-width: 80px;\"></td>\n");
      out.write("                        <td class=\"text-start\">");
      out.print(p.getProductName());
      out.write("</td>\n");
      out.write("                        <td>&#8377;");
      out.print(p.getProductPriceAfterDiscount());
      out.write("</td>\n");
      out.write("                        <td>\n");
      out.write("                            <a href=\"WishlistServlet?uid=");
      out.print(u1.getUserId());
      out.write("&pid=");
      out.print(p.getProductId());
      out.write("&op=delete\" class=\"btn btn-danger btn-sm\">Remove</a>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                    }
                    
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        ");

        }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                    <div id=\"order\" style=\"display: none;\">\n");
      out.write("                        ");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

userModel u2 = (userModel) session.getAttribute("activeUser");
if (u2 == null) {
    messageModel message = new messageModel("You are not logged in! Login first!!", "error", "alert-danger");
    session.setAttribute("message", message);
    response.sendRedirect("login.jsp");
    return;  
}
orderDAO orderDao = new orderDAO(DatabaseUtil.getConnection());
orderedProductDAO ordProdDao = new orderedProductDAO(DatabaseUtil.getConnection());

List<orderModel> orderList = orderDao.getAllOrderByUserId(u2.getUserId());

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("    <meta charset=\"UTF-8\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("    <title>My Orders</title>\n");
      out.write("    <!-- Bootstrap CSS -->\n");
      out.write("    <link href=\"https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("    <!-- Custom CSS -->\n");
      out.write("    <link href=\"styles/custom.css\" rel=\"stylesheet\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div class=\"container mt-5\">\n");
      out.write("        ");

        if (orderList == null || orderList.size() == 0) {
        
      out.write("\n");
      out.write("        <div class=\"text-center\">\n");
      out.write("            <img src=\"Images/empty-cart.png\" alt=\"No Orders\" class=\"img-fluid\" style=\"max-width: 250px;\">\n");
      out.write("            <h4 class=\"mt-3\">No Orders Found</h4>\n");
      out.write("            <p class=\"lead\">It looks like you haven't placed any orders yet!</p>\n");
      out.write("        </div>\n");
      out.write("        ");

        } else {
        
      out.write("\n");
      out.write("        <div class=\"mb-4\">\n");
      out.write("            <h4 class=\"text-primary border-bottom pb-2\">My Orders</h4>\n");
      out.write("            <p class=\"text-muted\">Here are all your recent orders. Review your past purchases and their details.</p>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"table-responsive\">\n");
      out.write("            <table class=\"table table-striped table-hover\">\n");
      out.write("                <thead class=\"table-secondary\">\n");
      out.write("                    <tr class=\"text-center\">\n");
      out.write("                        <th>Product</th>\n");
      out.write("                        <th>Order ID</th>\n");
      out.write("                        <th>Name</th>\n");
      out.write("                        <th>Quantity</th>\n");
      out.write("                        <th>Total Price</th>\n");
      out.write("                        <th>Date and Time</th>\n");
      out.write("                        <th>Payment Type</th>\n");
      out.write("                        <th>Status</th>\n");
      out.write("                    </tr>\n");
      out.write("                </thead>\n");
      out.write("                <tbody>\n");
      out.write("                    ");

                    for (orderModel order : orderList) {
                        List<orderedProductModel> ordProdList = ordProdDao.getAllOrderedProduct(order.getId());
                        for (orderedProductModel orderProduct : ordProdList) {
                    
      out.write("\n");
      out.write("                    <tr class=\"text-center\">\n");
      out.write("                        <td><img src=\"Product_imgs/");
      out.print(orderProduct.getImage());
      out.write("\" alt=\"");
      out.print(orderProduct.getName());
      out.write("\" class=\"img-thumbnail\" style=\"max-width: 80px;\"></td>\n");
      out.write("                        <td>");
      out.print(order.getOrderId());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(orderProduct.getName());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(orderProduct.getQuantity());
      out.write("</td>\n");
      out.write("                        <td>&#8377;");
      out.print(orderProduct.getPrice() * orderProduct.getQuantity());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(order.getDate());
      out.write("</td>\n");
      out.write("                        <td>");
      out.print(order.getPayementType());
      out.write("</td>\n");
      out.write("                        <td class=\"fw-semibold text-success\">");
      out.print(order.getStatus());
      out.write("</td>\n");
      out.write("                    </tr>\n");
      out.write("                    ");

                        }
                    }
                    
      out.write("\n");
      out.write("                </tbody>\n");
      out.write("            </table>\n");
      out.write("        </div>\n");
      out.write("        ");

        }
        
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Bootstrap JS and dependencies -->\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js\"></script>\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.3.0/js/bootstrap.min.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("            <!-- End of Main Content -->\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <!-- Modals -->\n");
      out.write("    <!-- Change Address Modal -->\n");
      out.write("    <div class=\"modal fade\" id=\"changeAddressModal\" tabindex=\"-1\" aria-labelledby=\"changeAddressModalLabel\" aria-hidden=\"true\">\n");
      out.write("        <div class=\"modal-dialog\">\n");
      out.write("            <div class=\"modal-content\">\n");
      out.write("                <div class=\"modal-header\">\n");
      out.write("                    <h5 class=\"modal-title\" id=\"changeAddressModalLabel\">Change Address</h5>\n");
      out.write("                    <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                </div>\n");
      out.write("                <form action=\"updateuser\" method=\"post\">\n");
      out.write("                    <input type=\"hidden\" name=\"operation\" value=\"changeAddress\">\n");
      out.write("                    <div class=\"modal-body\">\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"address\" class=\"form-label\">Address</label>\n");
      out.write("                            <textarea id=\"address\" name=\"user_address\" rows=\"3\" placeholder=\"Enter Address (Area and Street)\" class=\"form-control\" required></textarea>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"city\" class=\"form-label\">City</label>\n");
      out.write("                            <input id=\"city\" class=\"form-control\" type=\"text\" name=\"city\" placeholder=\"City/District/Town\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"pincode\" class=\"form-label\">Pincode</label>\n");
      out.write("                            <input id=\"pincode\" class=\"form-control\" type=\"number\" name=\"pincode\" placeholder=\"Pincode\" maxlength=\"6\" required>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"mb-3\">\n");
      out.write("                            <label for=\"state\" class=\"form-label\">State</label>\n");
      out.write("                            <select id=\"state\" name=\"state\" class=\"form-select\">\n");
      out.write("                                <option selected>--Select State--</option>\n");
      out.write("                                <option value=\"Andaman &amp; Nicobar Islands\">Andaman &amp; Nicobar Islands</option>\n");
      out.write("                                <option value=\"Andhra Pradesh\">Andhra Pradesh</option>\n");
      out.write("                                <option value=\"Arunachal Pradesh\">Arunachal Pradesh</option>\n");
      out.write("                                <option value=\"Assam\">Assam</option>\n");
      out.write("                                <option value=\"Bihar\">Bihar</option>\n");
      out.write("                                <option value=\"Chandigarh\">Chandigarh</option>\n");
      out.write("                                <option value=\"Chhattisgarh\">Chhattisgarh</option>\n");
      out.write("                                <option value=\"Dadra &amp; Nagar Haveli &amp; Daman &amp; Diu\">Dadra &amp; Nagar Haveli &amp; Daman &amp; Diu</option>\n");
      out.write("                                <option value=\"Delhi\">Delhi</option>\n");
      out.write("                                <option value=\"Goa\">Goa</option>\n");
      out.write("                                <option value=\"Gujarat\">Gujarat</option>\n");
      out.write("                                <option value=\"Haryana\">Haryana</option>\n");
      out.write("                                <option value=\"Himachal Pradesh\">Himachal Pradesh</option>\n");
      out.write("                                <option value=\"Jammu &amp; Kashmir\">Jammu &amp; Kashmir</option>\n");
      out.write("                                <option value=\"Jharkhand\">Jharkhand</option>\n");
      out.write("                                <option value=\"Karnataka\">Karnataka</option>\n");
      out.write("                                <option value=\"Kerala\">Kerala</option>\n");
      out.write("                                <option value=\"Ladakh\">Ladakh</option>\n");
      out.write("                                <option value=\"Lakshadweep\">Lakshadweep</option>\n");
      out.write("                                <option value=\"Madhya Pradesh\">Madhya Pradesh</option>\n");
      out.write("                                <option value=\"Maharashtra\">Maharashtra</option>\n");
      out.write("                                <option value=\"Manipur\">Manipur</option>\n");
      out.write("                                <option value=\"Meghalaya\">Meghalaya</option>\n");
      out.write("                                <option value=\"Mizoram\">Mizoram</option>\n");
      out.write("                                <option value=\"Nagaland\">Nagaland</option>\n");
      out.write("                                <option value=\"Odisha\">Odisha</option>\n");
      out.write("                                <option value=\"Puducherry\">Puducherry</option>\n");
      out.write("                                <option value=\"Punjab\">Punjab</option>\n");
      out.write("                                <option value=\"Rajasthan\">Rajasthan</option>\n");
      out.write("                                <option value=\"Sikkim\">Sikkim</option>\n");
      out.write("                                <option value=\"Tamil Nadu\">Tamil Nadu</option>\n");
      out.write("                                <option value=\"Telangana\">Telangana</option>\n");
      out.write("                                <option value=\"Tripura\">Tripura</option>\n");
      out.write("                                <option value=\"Uttarakhand\">Uttarakhand</option>\n");
      out.write("                                <option value=\"Uttar Pradesh\">Uttar Pradesh</option>\n");
      out.write("                                <option value=\"West Bengal\">West Bengal</option>\n");
      out.write("                            </select>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"modal-footer\">\n");
      out.write("                        <button type=\"button\" class=\"btn btn-secondary\" data-bs-dismiss=\"modal\">Close</button>\n");
      out.write("                        <button type=\"submit\" class=\"btn btn-primary\">Save</button>\n");
      out.write("                    </div>\n");
      out.write("                </form>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <!-- End of Change Address Modal -->\n");
      out.write("\n");
      out.write("    <!-- Add other modals here if needed -->\n");
      out.write("\n");
      out.write("    <script>\n");
      out.write("        $(document).ready(function() {\n");
      out.write("            $('#profile-btn').click(function() {\n");
      out.write("                $('#profile').show();\n");
      out.write("                $('#wishlist').hide();\n");
      out.write("                $('#order').hide();\n");
      out.write("                $(this).addClass('cus-active');\n");
      out.write("                $('#wishlist-btn').removeClass('cus-active');\n");
      out.write("                $('#order-btn').removeClass('cus-active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#wishlist-btn').click(function() {\n");
      out.write("                $('#wishlist').show();\n");
      out.write("                $('#profile').hide();\n");
      out.write("                $('#order').hide();\n");
      out.write("                $(this).addClass('cus-active');\n");
      out.write("                $('#profile-btn').removeClass('cus-active');\n");
      out.write("                $('#order-btn').removeClass('cus-active');\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            $('#order-btn').click(function() {\n");
      out.write("                $('#order').show();\n");
      out.write("                $('#profile').hide();\n");
      out.write("                $('#wishlist').hide();\n");
      out.write("                $(this).addClass('cus-active');\n");
      out.write("                $('#profile-btn').removeClass('cus-active');\n");
      out.write("                $('#wishlist-btn').removeClass('cus-active');\n");
      out.write("            });\n");
      out.write("        });\n");
      out.write("    </script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
